# Generated by Django 4.1.7 on 2023-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantityType',
            field=models.CharField(choices=[('QTY', 'qty'), ('GR', 'gr'), ('KG', 'kg'), ('ML', 'ml'), ('L', 'l')], default='QTY', max_length=3),
        ),
    ]
